# Hook file copies certificate, sets domain name in turnserver.conf, and restarts coturn
- name: Run coturn cert renewal hook
  environment:
    RENEWED_DOMAINS: "{{ inventory_hostname }}"
    RENEWED_LINEAGE: "/etc/letsencrypt/live/{{ inventory_hostname }}"
  ansible.builtin.shell:
    cmd: "/etc/letsencrypt/renewal-hooks/deploy/certbot.sh"
