- name: Create directory for local systemd-system overrides
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: directory
    mode: "0755"

- name: Enable systemd watchdog
  ansible.builtin.copy:
    src: "system-override.conf"
    dest: "/etc/systemd/system.conf.d/local.conf"
    mode: "0644"
  notify: Reread systemd configs
