- name: Install Jitsi-Meet-Turnserver
  apt:
    pkg: [ "jitsi-meet-turnserver" ]

- name: Set static-auth-secret
  lineinfile:
    path: "/etc/turnserver.conf"
    regexp: "^static-auth-secret="
    line: "static-auth-secret={{ turnpwd }}"
  notify: restart coturn
