- name: Set Hostname for Videobridge websocket in jvb.conf
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/jvb.conf
    regexp: '^(\s*)domain =.*:443'
    backrefs: true
    line: '\1domain = "{{ inventory_hostname }}:443"'
  notify:
    - Restart jitsi-videobridge2

- name: Set xmpp domain for jvb user in jvb.conf
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/jvb.conf
    regexp: '^(\s*)DOMAIN=".*"'
    backrefs: true
    line: '\1DOMAIN="auth.{{ inventory_hostname }}"'
  notify:
    - Restart jitsi-videobridge2

- name: Set xmpp password for jvb user in jvb.conf
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/jvb.conf
    regexp: '^(\s*)PASSWORD=".*"'
    backrefs: true
    line: '\1PASSWORD="{{ jvbpwd }}"'
  notify:
    - Restart jitsi-videobridge2

- name: Set xmpp MUC jid in jvb.conf
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/jvb.conf
    regexp: '^(\s*)MUC_JIDS=".*"'
    backrefs: true
    line: '\1MUC_JIDS="jvbbrewery@internal.auth.{{ inventory_hostname }}"'
  notify:
    - Restart jitsi-videobridge2

- name: Replace Jitsi STUN server with ours in jvb.conf
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/jvb.conf
    regexp: '^(\s*)addresses = \[".*'
    backrefs: true
    line: '\1addresses = ["{{ inventory_hostname }}:3478"]'
  notify:
    - Restart jitsi-videobridge2

- name: Check if REST API is enabled for statistics and monitoring
  ansible.builtin.lineinfile:
    state: absent
    path: /etc/jitsi/videobridge/jvb.conf
    regexp: "^\\s*apis { rest { enabled = true } }"
  check_mode: true
  changed_when: false
  register: rest_api

- name: Enable REST API
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/jvb.conf
    insertafter: "videobridge {"
    line: "    apis { rest { enabled = true } }"
  when: not rest_api.found
  notify:
    - Restart jitsi-videobridge2

- name: Decrease Videobridge loglevel
  ansible.builtin.lineinfile:
    path: /etc/jitsi/videobridge/logging.properties
    regexp: '^\.level='
    line: ".level=WARNING"
  notify:
    - Restart jitsi-videobridge2
