- name: Update-ca-certificates
  ansible.builtin.command:
    cmd: update-ca-certificates -f

- name: Restart prosody
  ansible.builtin.service:
    name: prosody.service
    state: restarted

- name: Restart jitsi-videobridge2
  ansible.builtin.service:
    name: jitsi-videobridge2.service
    state: restarted
