- name: Create jicofo configuration
  ansible.builtin.template:
    src: jicofo.conf.j2
    dest: /etc/jitsi/jicofo/jicofo.conf
    mode: '0640'
    owner: jicofo
    group: jitsi
  notify:
    - Restart jicofo

- name: Decrease Jicofo loglevel
  ansible.builtin.lineinfile:
    path: "/etc/jitsi/jicofo/logging.properties"
    regexp: '^\.level='
    line: ".level=WARNING"
  notify: Restart jicofo
