- name: Install unattended-upgrades package
  ansible.builtin.apt:
    pkg: "unattended-upgrades"
    state: present
    update_cache: true
    cache_valid_time: 1800

- name: Enable unattended upgrades
  ansible.builtin.template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    mode: "0644"
  notify: Run apt.systemd.daily

- name: Configure unattended upgrades on Debian
  ansible.builtin.template:
    src: 50unattended-upgrades-debian.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"

- name: Do not cache packages installed with apt-get
  ansible.builtin.template:
    src: 01keep-debs.j2
    dest: /etc/apt/apt.conf.d/01keep-debs
    mode: "0644"

- name: Let restart server once a week if required
  ansible.builtin.cron:
    name: weekly restart
    weekday: "0"
    hour: "3"
    minute: "30"
    job: "if [ -f /var/run/reboot-required ]; then /sbin/shutdown -r +5; fi"
