- name: Install unattended-upgrades package
  apt:
    pkg: "unattended-upgrades"
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Enable unattended upgrades
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    mode: "0644"
  notify: run apt.systemd.daily

- name: Configure unattended upgrades on Debian
  template:
    src: 50unattended-upgrades-debian.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"

- name: Let restart server once a week if required
  cron:
    name: weekly restart
    weekday: "0"
    hour: "3"
    minute: "30"
    job: "if [ -f /var/run/reboot-required ]; then /sbin/shutdown -r +5; fi"
