- name: Install unattended-upgrades package
  ansible.builtin.apt:
    pkg: "unattended-upgrades"
    state: present
    update_cache: true
    cache_valid_time: 1800

- name: Enable unattended upgrades
  ansible.builtin.template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    mode: "0644"
  notify: Run apt.systemd.daily

- name: Configure unattended upgrades on Debian
  ansible.builtin.template:
    src: 50unattended-upgrades-debian.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"

- name: Do not cache packages installed with apt-get
  ansible.builtin.template:
    src: 01keep-debs.j2
    dest: /etc/apt/apt.conf.d/01keep-debs
    mode: "0644"

- name: Create directories for systemd overrides
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/systemd/system/apt-daily.timer.d
    - /etc/systemd/system/apt-daily-upgrade.timer.d

- name: Override systemd timer for downloading updates
  ansible.builtin.template:
    src: apt-daily.j2
    dest: /etc/systemd/system/apt-daily.timer.d/ansible.conf
    mode: "0644"
  notify: Reread systemd configs

- name: Override systemd for installing downloaded updates (incl. reboot, if required)
  ansible.builtin.template:
    src: apt-daily-upgrade.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/ansible.conf
    mode: "0644"
  notify: Reread systemd configs
