- name: Create directory for system overrides
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d/"
    state: directory
    mode: "0755"

- name: Set system limits
  ansible.builtin.copy:
    src: "system.conf"
    dest: "/etc/systemd/system.conf.d/jitsi-meet.conf"
    mode: "0644"
  notify:
    - Reread systemd configs

- name: Create directories for systemd overrides
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
    mode: "0755"
  loop:
    - nginx
    - prosody
    - jicofo
    - jibri-icewm
    - jibri-xorg
    - nagios-nrpe-server

- name: Create systemd overrides to restart services automatically on failure
  ansible.builtin.copy:
    src: restart-on-failure.service
    dest: /etc/systemd/system/{{ item }}.service.d/restart-on-failure.conf
    mode: "0644"
  loop:
    - nginx
    - prosody
    - jicofo
    - jibri-icewm
    - jibri-xorg
    - nagios-nrpe-server
  notify:
    - Reread systemd configs
