- name: Create directory for local journald overrides
  ansible.builtin.file:
    path: "/etc/systemd/journald.conf.d"
    state: directory
    mode: "0755"

- name: Limit journald logging to 14 days
  ansible.builtin.copy:
    src: "journald-override.conf"
    dest: "/etc/systemd/journald.conf.d/local.conf"
    mode: "0644"
  notify: Restart journald
