- name: Install Certbot
  apt:
    pkg: [ 'certbot', 'python3-certbot-nginx' ]

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ item }}/cert.pem"
  register: letsencrypt_cert
  loop: "{{ ( [ inventory_hostname, turns_hostname ] + jitsi.domain_aliases | default([]) ) | select('defined') | list }}"

- name: Stop Nginx to allow certbot to generate a cert
  service:
    name: "nginx"
    state: stopped
  when: letsencrypt_cert.results | selectattr('stat.exists','equalto', false) | list | count > 0

- name: Generate new certificate
  command: >
    certbot certonly --standalone --noninteractive --agree-tos --email {{ admin.email }}
    -d {{ item }}
  loop: "{{ ( [ inventory_hostname, turns_hostname ] + jitsi.domain_aliases | default([]) ) | select('defined') | list }}"
  args:
    creates: "/etc/letsencrypt/live/{{ item }}/cert.pem"
  notify:
    - run nginx cert renewal hook
    - run coturn cert renewal hook

- name: Start Nginx after cert has been generated
  service:
    name: "nginx"
    state: started
  when: letsencrypt_cert.results | selectattr('stat.exists','equalto', false) | list | count > 0

- name: Add hook to certbot to reload Nginx after certificate renewal
  template:
    src: "renewal-hook-nginx.sh.j2"
    dest: "/etc/letsencrypt/renewal-hooks/post/nginx.sh"
    mode: 0770
